### ISSUE TITLE
Open the report

### ISSUE THREAD

**Issue by tobiastom** [little-green-man/nova-taskfinder#7]
It's really nice to have the tasks available automatically. Unfortunately I cannot find a way to open the report. For example with `yarn start` I'd like to see error messages (or notices).

**Comment by kurucu** [comment]
Hi @tobiastom. 

This extension allows Nova to do as much work natively as possible, all it does is automatically register the commands for you.

To see the reports, you need to use Nova's built in tool. If you check out the side bars, you can find one called Reports:

<img width="449" alt="Screenshot 2022-01-23 at 11 49 07" src="https://user-images.githubusercontent.com/1073323/150660420-bc7a6aba-76bd-4bab-bcc9-eb688b3245f0.png">

And then you can select the reports, like this example:

<img width="1640" alt="Screenshot 2022-01-23 at 11 50 56" src="https://user-images.githubusercontent.com/1073323/150660428-dbf62ec5-afb7-4a16-a387-64294090889b.png">

The Reports button can be dragged to the top to make it a favourite/shortcut.

**Comment by tobiastom** [comment]
I did not know that. Thank you for the hint.

Is there an API to open the report automatically? One could define scripts inside the settings that should open the report automatically.

So I write `npm run development` into that list and your extension would know to open the report once this is started?

Just an idea, opening the report manually works for me for now.

**Comment by kurucu** [comment]
I've taken a look and can't see an API for that. If you know otherwise, share it here and I'll implement your idea.

**Comment by tobiastom** [comment]
I cannot find one either. Thanks for looking.
