### ISSUE TITLE
NPM "doesn't exist"

### ISSUE THREAD

**Issue by claycle** [little-green-man/nova-taskfinder#8]
Getting the following error: 

<img width="340" alt="image" src="https://user-images.githubusercontent.com/419840/153023337-ed6fe4bd-5883-4360-9b3c-9c0f8a7a471e.png">

Get a "can't find npm" error, despite npm being in my $PATH, via nvm. Nova doesn't have a problem find npm (I can make a Nova build task that properly executes "npm run build" for example).

```
 % node --version
v16.13.1
% nvm version
v16.13.1
% which npm
/Users/claycle/.nvm/versions/node/v16.13.1/bin/npm
```

**Comment by kisonay** [comment]
I'm having the same issue, and it seems related to NVM per https://github.com/little-green-man/nova-taskfinder/issues/5 

I have not figured out a work around yet.

**Comment by kurucu** [comment]
Hi @kisonay, you need to set the path to NPM in the extension or project settings.
It's a bug (or feature) of Nova that the default environment isn't used (for tasks, the in-app terminal is run in user space), they were looking into it but nothing to date, so you need to provide the extension with the full path manually.

I'm all ears if you have better ideas.

**Comment by kurucu** [comment]
I think this is fixed now. The shell paths are used, and the ability to set a manual path has been removed as result.

**Comment by kurucu** [comment]
Update to v3.1.0 to check it out, thanks!
