### ISSUE TITLE
Taskfile support

### ISSUE THREAD

**Issue by cweagans** [little-green-man/nova-taskfinder#9]
I use https://taskfile.dev for a lot of stuff -- it'd be really cool to auto-register all of my tasks in Nova!

**Comment by cweagans** [comment]
Ideally, this could be done by calling `task --list` instead of trying to parse the YAML directly. There are a lot of weird little gotchas about included taskfiles and stuff that would be better to not reimplement.

**Comment by kurucu** [comment]
Hey @cweagans - I'll look into it - cool idea, thanks!

**Comment by kurucu** [comment]
Hi. I think I have this working in the current release - check the extension library and update to v3.1.0 and let me know how it goes!

**Comment by kurucu** [comment]
With no feedback - I assume this is working and closed.
